apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      imagePullSecrets:
        - name: dockerhub-secret        # ← matches secret created in stage 5
      containers:
        - name: java-app                # ← must match CONTAINER_NAME in pipeline
          image: murthy4797/javaapp:IMAGE_TAG   # ← sed replaces this at runtime
          imagePullPolicy: Always       # ← always pull fresh image
          ports:
            - containerPort: 8080
