
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZnVrOG9nNnFCREl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1qWXdNekE1TXpkYUZ3MHpOakF6TWpNd016RTBNemRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURxa2tHME43V2g4c29lMG95SHZCSzc2bi9KZTUzL2c0VlorbTUvTmduVzBVYk5ya05oUUV1VlA0KzUKK0dubDVUQTJxOXRnVWdiUXJKWnJpamN4bkxFUTJnbkNhRjBuR2xHOE1jMkdFdXU4SERJTVQ0bDJyWFBqc2lnawpEd09Eb3JtR29sc3hlSmhha2x5ZENINFloVEtBa3dWRWtwVkRURG9GM1hEdml0K3U2dis2V0tMMlhRUHhoNlBVCmgzMnAvZDJUb25RQlZ4TVNkVFhzVUhIbS9CVncvK05RcTZCSEhBVjlUS20zWmRibE9xSHZqUXFDV2tQNmV4ZnoKZllaRlBBRVFYam5EUUtjakZyOFA5N2JnY2FGTm13dm1pRmdwckFucDN2QTRKNzg3bStPYmRoRWhUejdJRkpXcQp1Y29zRTRrRVBzeWRESzNQc2FTT3dWczI0SWdsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZjBGNU4vbTNETHh1MHF0SitoQWlKVTB2S1RUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQm1HYzd4VXg2TwpRTGRyYzRoT0lsYjRGNTRsTG94dUJYVXNWVVpIbkl0dHAxQngzaTJSRVNCOUJJbXBZZkRoNUg5U3VoeVF1bkJNCmdOZU52U2V0b05qNnVDdVg0MUM4dnRzOElOSDFiUWJ3cWQzdEpYQmlubVV2QVhXT2JNK0Qya0ZDR2JGclpCRDQKaExFQ0I1eE9vZEVjWlJqSVNEdUdEaW9NSm0yVStVZmFRdnd5aytmeEFtVFRNcjdGRWYrNU0zU2xxbi9vSnlkcQpsY0N3L2xFK05JZXdock9BS3JXSGJub2FzdnNBLzRpdGs1MVVYaGtmNHhwVTMwYms5SzkyZmx4VUx0ckZvd1JiCnJCRy9ieEVzckMvcHY1dmN0L3MyN2E2MVFQU2pDcjlIbHRFTTRZVktkVDFBLyswZkVsbTZLUlpJZEQvbVFNYnIKMU45V3Z3UWFxT1dRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://926495ef-ceb6-4ef9-b96a-a3855eb39232.in-maa-1-gw.linodelke.net:443
  name: lke584297

users:
- name: lke584297-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImlNbTEyYnJPMnNLOWJBdG5kaDFES0JmTHlNcnBCOXlZMWQ1M1NnWjN1UWsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZ2wycTQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmIzMTE1NzItYzE0NS00NjE4LWIwNTYtYmI2NTAwZjNhNzNkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.CCiOIj7aCXPZFjYZJxFm0LqLTcZvXywYvnk-cleMSHtCq6GGy7ifa9kL_fMH_Ny8KwLwlhJJf8gP3icGNH98dsyHny3L7TOYapfYnhuOxs0ps3WSXOA-VCZPGYbMSw9CuWjRR09OCBfscHwB7VTQ0FLJCthJZWamsxUo_65Va-RMdmltZXGtSEWvDyj7WNYZ9iU5cMkwuKh7WU7haiDRUoknWqVN5RwwuSF1TRqMyynOLUR2zb7P1eV_xVPj2r8lOYkJL6kO8neft9rXsIAHgEf048aDeLQIJgkIqDB-bExzedGADH4alZ7781ItV2YuSu-ILqiCN5J-i79d1d-NWQ

contexts:
- context:
    cluster: lke584297
    namespace: default
    user: lke584297-admin
  name: lke584297-ctx

current-context: lke584297-ctx
