
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZGdybVNQenlyT1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1qVXdPVE0wTlRaYUZ3MHpOakF6TWpJd09UTTVOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMvSGJWSTJlaHQ4Q3F6QUV1bUozak54MUNiNDk2NEFqSEFwdG5sQlEvbkg0dzZxVXdCYWhSdGJFUTMKOThnLzNBQ3VMeXN6NkJqUWg0U3d5NVlZa1IyQ2dXSldjenI0RjhrRFlrSmpLcVdWVURlZ3FZVWEzbFhZNnhEMgpMSWtaV0h0MzR2UDcxY0hTWmkyOE9DMHR1di9FV3VSWE11L3oyR3pLSk5CaDFDS2VOeXNUNHZ2b2l5MjZ3aEIzCkNSa3VGKyszVGFOaVBrZW5EdE1KSklManJhMHZXWDZCSGZCNTZ5Y29kWUNnNWtTSlFzd01YTmc4V21WdFlJV1kKdzlOM1phcE5JNkkxakNXaEZYSVZMNHpDL3NNZ3pwSVJlOEFXamp5TVU0NDk0ZGFBQVVNRlZRZFhhcDJqRzcwOApFN2swZVdtVVJmNHB1OC9YQ0xaK1YxdElBempyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTLzZxV3I1WnI2aGRCeTlOMFN4bU0wYVR4Kzd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU1BUWs1bi8wTgpDdU5BQVE1RDduTUg3YzJiUzFnQSszKzREdGlteHFJaHpMN0lra1hjdUhqbTU5VnJkS0syLzZkeG00S0ZRSzhVCmI4RS9wUnpJbnRBRXFPUThoM0RGZE1mY0NKTXQyaklKRTU3RDBhVU9OMzgydE16L2Y3aEYvSEFrVGk2ZEp5b3EKQVdacG1VTklhcWZraERhZkY2aEs2bEdWNW9TQVBDSWttODZQYXZSbCthNUlyNmdPejFpankrbnQ3eWhWSUVsQgpodjcrdmM3K09PaDh2eUlUOG1NMjhXbFFTR0VtY3FydHdrdkFDSm1CYVUvcVpONUJ2bzA0blZoSWJSeDQ0bmhxClN0ekcrT2ZKQ0s5d05GSUo5Vm0zZDhraW1xNFZCMExVVWhMY3FrdzhmV1VlVHpOd3AzQlU0L2hJSTNLait2R3IKbFVmZXVHUG1rVTZ5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://39e25879-2298-4a05-987c-c0eb28692c08.in-maa-1-gw.linodelke.net:443
  name: lke583911

users:
- name: lke583911-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldCbG5YbjdsRnl4WWhFR09nWkFWOUxBby1GcGhVTlVGM25qMFIwV2ZKeHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4ta2Y4N2giLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDg3NTUzMjYtMGQxOC00ZjVhLWIzZmMtZjE2MzExYjAxOGI5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.jm_n4ZAXMkpIsr5ZTKBJyAgOoDkhpmYI32ePlwblTbP0ZZL9SSPiNho5P3f3ob4kYarUmqJr4UZ7QE-PXzPqJlZbrfEuW_GmokVHtfG9oKPUf5D61v1LDUD76bKMeXnQ7nABEtjtC1reutfF8L4XE1Jt3P13gLM8G6KtVybI93oul6LMMgVeQOkAUOiHeHY2j2DuxtkStmN9Vx73nub_kr_WL1C3yn-2VUzinz6U-MRXUzYdisbk1fE7bbb_0cyVW0Ejp2DUIcgMCNwEYDFup6mlbzyODY0buJjGMprm7c_SDgsRgRur5gf3IuflzM1yyvWEyKY9M9-MpPFSQPP54w

contexts:
- context:
    cluster: lke583911
    namespace: default
    user: lke583911-admin
  name: lke583911-ctx

current-context: lke583911-ctx
